@host = http://localhost
@port = 8081
@baseUrl = {{host}}:{{port}}

############################# USERS FLOW ####################
###
# 1) Create a new user
# Save the returned _id and use it as {{userId}} in the next requests.
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "name": "Test Test2",
  "email": "test.test2+1@gmail.com",
  "password": "123456"
}

###
# 2) Get all users
# Used to verify the user was created successfully.
GET {{baseUrl}}/users/All

###
# 3) Get a single user by id
@userId = 696b95a0cd7e9100129c4e4b
GET {{baseUrl}}/users/{{userId}}

###
# 4) Update an existing user
# Updates user details based on the given id.
PUT {{baseUrl}}/users/update
Content-Type: application/json

{
  "id": "{{userId}}",
  "name": "Updated1",
  "email": "updated1@gmail.com",
  "password": "123456"
}

###
# 5) Delete a user
# Removes the user from the database.
DELETE {{baseUrl}}/users/delete
Content-Type: application/json

{
  "id": "{{userId}}"
}

############################# POSTS FLOW ####################
###
# 1) Get all posts
GET {{baseUrl}}/posts

###
# 2) Get a single post by id
@postId = 696b9a48221fb92220188186
GET {{baseUrl}}/posts/{{postId}}

###
# 3) Get posts by uploader id
# Returns all posts created by a specific user.
@uploaderId = 696b95a0cd7e9100129c4e4b
GET {{baseUrl}}/posts/uploader?uploaderId={{uploaderId}}

###
# 4) Create a new post
# uploader must be an existing user id.
POST {{baseUrl}}/posts/create
Content-Type: application/json

{
  "title": "Post Title Test",
  "content": "Post content for API test",
  "comments": [],
  "uploader": "{{uploaderId}}"
}

###
# 5) Update a post by id
PUT {{baseUrl}}/posts/update/{{postId}}
Content-Type: application/json

{
  "title": "Post Title Updated1",
  "content": "Updated post content"
}

###
# 6) Delete a post
# Also removes all related comments (according to controller logic).
DELETE {{baseUrl}}/posts/delete
Content-Type: application/json

{
  "id": "{{postId}}"
}

############################# COMMENTS FLOW ####################
###
# 1) Get all comments for a specific post
@postIdForComments = 696b9a4c221fb92220188188
GET {{baseUrl}}/comments/{{postIdForComments}}

###
# 2) Create a new comment
# Requires a valid userId and postId.
POST {{baseUrl}}/comments/create
Content-Type: application/json

{
  "userId": "696b95a0cd7e9100129c4e4b",
  "postId": "696ba54e9f012c24989b7d13",
  "text": "Comment text for API test"
}

###
# 3) Update a comment by id
@commentId = 696ba4a49f012c24989b7d0a
PUT {{baseUrl}}/comments/update
Content-Type: application/json

{
  "id": "{{commentId}}",
  "text": "Updated comment text"
}

###
# 4) Delete a comment by id
# Removes the comment from both the comments collection and the post.
DELETE {{baseUrl}}/comments/delete
Content-Type: application/json

{
  "id": "{{commentId}}"
}
